### ISSUE TITLE
Invalid `main` specified

### ISSUE THREAD

**Issue by TimoGlastra** [jfromaniello/typedmap#1]
The `main field specifies `dist/index.js`, however the dist folder has cjs/esm subdirectories. These are correctly typed in the `exports` field. 

This is causing issues in react native. Can we update the `main` to `dist/cjs/indx.js`?

**Comment by jfromaniello** [comment]
Thank you for reporting this, the `main` field is not necessary. There is an export map for every module system.

**Comment by TimoGlastra** [comment]
Thanks for the quick fix. I'll test it tomorrow in our app
